CREATE TABLE "symmetric_cart_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "symmetric_cart_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sessionId" varchar(255) NOT NULL,
	"eventId" varchar(255) NOT NULL,
	"eventTitle" varchar(500) NOT NULL,
	"eventSlug" varchar(255) NOT NULL,
	"price" integer NOT NULL,
	"currency" varchar(3) DEFAULT 'USD' NOT NULL,
	"quantity" integer DEFAULT 1 NOT NULL,
	"startDate" date,
	"endDate" date,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "symmetric_order_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "symmetric_order_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"orderId" integer NOT NULL,
	"eventId" varchar(255) NOT NULL,
	"eventTitle" varchar(500) NOT NULL,
	"eventSlug" varchar(255) NOT NULL,
	"price" integer NOT NULL,
	"currency" varchar(3) DEFAULT 'USD' NOT NULL,
	"quantity" integer DEFAULT 1 NOT NULL,
	"startDate" date,
	"endDate" date,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "symmetric_order" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "symmetric_order_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sessionId" varchar(255) NOT NULL,
	"stripeSessionId" varchar(255),
	"stripePaymentIntentId" varchar(255),
	"status" varchar(50) DEFAULT 'pending' NOT NULL,
	"totalAmount" integer NOT NULL,
	"currency" varchar(3) DEFAULT 'USD' NOT NULL,
	"customerEmail" varchar(255),
	"customerName" varchar(255),
	"customerCompany" varchar(255),
	"customerPhone" varchar(50),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "symmetric_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "symmetric_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "symmetric_order_item" ADD CONSTRAINT "symmetric_order_item_orderId_symmetric_order_id_fk" FOREIGN KEY ("orderId") REFERENCES "public"."symmetric_order"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "session_id_idx" ON "symmetric_cart_item" USING btree ("sessionId");--> statement-breakpoint
CREATE INDEX "event_id_idx" ON "symmetric_cart_item" USING btree ("eventId");--> statement-breakpoint
CREATE INDEX "order_item_order_id_idx" ON "symmetric_order_item" USING btree ("orderId");--> statement-breakpoint
CREATE INDEX "order_item_event_id_idx" ON "symmetric_order_item" USING btree ("eventId");--> statement-breakpoint
CREATE INDEX "order_session_id_idx" ON "symmetric_order" USING btree ("sessionId");--> statement-breakpoint
CREATE INDEX "order_stripe_session_id_idx" ON "symmetric_order" USING btree ("stripeSessionId");--> statement-breakpoint
CREATE INDEX "order_status_idx" ON "symmetric_order" USING btree ("status");--> statement-breakpoint
CREATE INDEX "name_idx" ON "symmetric_post" USING btree ("name");