CREATE TABLE "symmetric_categories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "symmetric_categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"description" text,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "symmetric_categories_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "symmetric_media" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "symmetric_media_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"alt" varchar(255) NOT NULL,
	"url" varchar(500),
	"thumbnailUrl" varchar(500),
	"filename" varchar(255),
	"mimeType" varchar(100),
	"filesize" integer,
	"width" integer,
	"height" integer,
	"focalX" integer,
	"focalY" integer,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "symmetric_media_filename_unique" UNIQUE("filename")
);
--> statement-breakpoint
CREATE TABLE "symmetric_users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "symmetric_users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" varchar(255) NOT NULL,
	"resetPasswordToken" varchar(255),
	"resetPasswordExpiration" timestamp with time zone,
	"salt" varchar(255),
	"hash" varchar(255),
	"loginAttempts" integer DEFAULT 0,
	"lockUntil" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "symmetric_users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE INDEX "categories_slug_idx" ON "symmetric_categories" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "categories_created_at_idx" ON "symmetric_categories" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "categories_updated_at_idx" ON "symmetric_categories" USING btree ("updatedAt");--> statement-breakpoint
CREATE INDEX "media_filename_idx" ON "symmetric_media" USING btree ("filename");--> statement-breakpoint
CREATE INDEX "media_created_at_idx" ON "symmetric_media" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "media_updated_at_idx" ON "symmetric_media" USING btree ("updatedAt");--> statement-breakpoint
CREATE INDEX "users_email_idx" ON "symmetric_users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "users_created_at_idx" ON "symmetric_users" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "users_updated_at_idx" ON "symmetric_users" USING btree ("updatedAt");